### ISSUE TITLE
Midas Shapes

### ISSUE THREAD

**Issue by CrustaceanJ** [patrickvonplaten/controlnet_aux#2]
Hi, I tried to use a model from your repository and something went wrong.

```#py
from diffusers.utils import load_image
from controlnet_aux import MidasDetector

image = load_image(
    "https://avatars.mds.yandex.net/i?id=37a6363ac568a0b588aead66c7e1af48_l-5447357-images-thumbs&n=13"
)

midas = MidasDetector.from_pretrained("lllyasviel/ControlNet")

depth_map, image = midas(image)
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/crustacean/miniconda3/envs/dl_sd/lib/python3.10/site-packages/controlnet_aux/midas/__init__.py", line 34, in __call__
    depth = self.model(image_depth)[0]
  File "/home/crustacean/miniconda3/envs/dl_sd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/crustacean/miniconda3/envs/dl_sd/lib/python3.10/site-packages/controlnet_aux/midas/api.py", line 167, in forward
    prediction = self.model(x)
  File "/home/crustacean/miniconda3/envs/dl_sd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/crustacean/miniconda3/envs/dl_sd/lib/python3.10/site-packages/controlnet_aux/midas/midas/dpt_depth.py", line 108, in forward
    return super().forward(x).squeeze(dim=1)
  File "/home/crustacean/miniconda3/envs/dl_sd/lib/python3.10/site-packages/controlnet_aux/midas/midas/dpt_depth.py", line 71, in forward
    layer_1, layer_2, layer_3, layer_4 = forward_vit(self.pretrained, x)
  File "/home/crustacean/miniconda3/envs/dl_sd/lib/python3.10/site-packages/controlnet_aux/midas/midas/vit.py", line 59, in forward_vit
    glob = pretrained.model.forward_flex(x)
  File "/home/crustacean/miniconda3/envs/dl_sd/lib/python3.10/site-packages/controlnet_aux/midas/midas/vit.py", line 145, in forward_flex
    x = x + pos_embed
RuntimeError: The size of tensor a (25945) must match the size of tensor b (25620) at non-singleton dimension 1
```

**Comment by patrickvonplaten** [comment]
@jinwonkim93 could you take a look here re: https://github.com/patrickvonplaten/controlnet_aux/pull/1

**Comment by jinwonkim93** [comment]
Hi @CrustaceanJ . I have check your image and the size was (2206, 3000). please change the ratio of image.

example
```python
from diffusers.utils import load_image
from controlnet_aux import MidasDetector
import numpy as np

image = load_image(
    "https://avatars.mds.yandex.net/i?id=37a6363ac568a0b588aead66c7e1af48_l-5447357-images-thumbs&n=13"
)

W, H = image.size
resolution = 1024
if resolution < min(W, H):
    k = resolution / min(W, H)
    W *= k
    H *= k

W_new = int(np.round(W/64) * 64)
H_new = int(np.round(H/64) * 64)
image = image.resize((W_new, H_new))

midas = MidasDetector.from_pretrained("lllyasviel/ControlNet")

depth_map, image = midas(image)
```
