### ISSUE TITLE
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name'

### ISSUE THREAD

**Issue by onefish51** [patrickvonplaten/controlnet_aux#3]
when I load local ckpt
```python
from controlnet_aux import OpenposeDetector

model = OpenposeDetector.from_pretrained("./diffusers/ControlNet")
```

a error occurred :
```sh
Traceback (most recent call last):
  File "test_controlnet.py", line 105, in <module>
    model = OpenposeDetector.from_pretrained("./diffusers/ControlNet")
  File "/opt/conda/lib/python3.8/site-packages/controlnet_aux/open_pose/__init__.py", line 36, in from_pretrained
    body_model_path = hf_hub_download(pretrained_model_or_path, filename)
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    validate_repo_id(arg_value)
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 166, in validate_repo_id
    raise HFValidationError(
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './diffusers/ControlNet'. Use `repo_type` argument if needed.
```

**Comment by jinwonkim93** [comment]
.from_pretrained downloads from hugginface hub. 

try this
```python
open_pose = OpenposeDetector.from_pretrained("lllyasviel/ControlNet")
```

**Comment by onefish51** [comment]
but I want to use local ckpt, which I downloaded

**Comment by patrickvonplaten** [comment]
Hey @onefish51, 

If you want to load the model locally, you should just do:

```py
from controlnet_aux import OpenposeDetector
from controlnet_aux.open_pose.body import Body

body_model = Body("./diffusers/ControlNet/annotator/ckpts/body_pose_model.pth")
detector = OpenposeDetector(body_model)
```

**Comment by depyronick** [comment]
[https://github.com/huggingface/huggingface_hub/blob/f471a5bac0552d30f75d67b150443cae3d544b77/src/huggingface_hub/utils/_validators.py#L159](https://github.com/huggingface/huggingface_hub/blob/f471a5bac0552d30f75d67b150443cae3d544b77/src/huggingface_hub/utils/_validators.py#L159 )

```
    if repo_id.count("/") > 1:
        raise HFValidationError(
            "Repo id must be in the form 'repo_name' or 'namespace/repo_name':"
            f" '{repo_id}'. Use `repo_type` argument if needed."
        )
```

**Comment by patrickvonplaten** [comment]
Hey @depyronick,

Could you maybe open a new issue with a reproducible error message?
